### ISSUE TITLE
unable to open lesson resources from 'take a free tour' @home page

### ISSUE THREAD

**Issue by sumitmago** [OUPMATH/OxfrodMaths_Prod#1]
hi,
 I am trying to open learning content from 'take a free tour' link. it opens the classes -> chapter -> topic, but when I click on learning resources, it shows 'loading' pre -loader but shows the home page after that. it does not open learning content for the topic. Please check the video.

I am unable to upload the video. Sending it to manas on mail and uploading to FTP as well.

**Comment by sumitmago** [comment]
hi, hope someone is working to close this issue?

**Comment by manasghosh81** [comment]
I think this issue got resolved now after the URL redirect done .Please check and close it if it works as per the requirement.

**Comment by sumitmago** [comment]
Hi,
Its opening but taking time to load.

Thanks & Regards
Sumit Mago
Head (Digital Solutions) – Learning & Assessment
Oxford University Press
2nd Floor, Tower-1, Stellar Crest  Business Center, IT Park, C-25 Sector 62,  Noida
(D) - 0120-6718900 Extn - 214, (M) +91-9873299973

The ABC of Innovation:
Conceive
Believe
Achieve

**Comment by mayank2k2** [comment]
This is working in PROD so closing
