### ISSUE TITLE
Remedial are not being created

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfrodMaths_Prod#10]
New task created and assigned to student

![image](https://cloud.githubusercontent.com/assets/16239450/14662987/51321bee-06d9-11e6-9cd1-4bfe6cb1e41d.png)

Student completed the task but failed due to score 9% only.
remedial are not being generated for student, Ideally remedial should be created for the student.

**Comment by manasghosh81** [comment]
This has been done using job which runs at 12 am midnight everyday.Need to check and identify the issue using log

**Comment by manasghosh81** [comment]
@mayank2k2 :The scheduler job project has been restarted.
A remedial job has been created for username mohitgupta/Password@1.

We have created task which will completed on Saturday midnight,It will create remedial task for same student after that time.

**Comment by mayank2k2** [comment]
@manasghosh81 : Remedial are created but why 2 remedials created  for each homework. 
check the user:  Student 13 A/OUPMath@6141

![image](https://cloud.githubusercontent.com/assets/16239450/14974259/5b8e6c78-1110-11e6-887d-24aae2512482.png)

![image](https://cloud.githubusercontent.com/assets/16239450/14974264/724b1af6-1110-11e6-9e93-be7f8701e036.png)

![image](https://cloud.githubusercontent.com/assets/16239450/14974240/f84d4008-110f-11e6-9797-9de364b9baa0.png)

![image](https://cloud.githubusercontent.com/assets/16239450/14974254/41db647a-1110-11e6-987d-475173b417a8.png)

**Comment by pankaj44** [comment]
We are looking into it.

**Comment by pankaj44** [comment]
Job was manually run twice during testing purpose. Hence two remedial were created.

**Comment by mayank2k2** [comment]
yesterday i completed  homework for task
![image](https://cloud.githubusercontent.com/assets/16239450/15004882/45c37f76-11da-11e6-8a68-ab906370e2f8.png)

but no remedials have been created.

**Comment by pankaj44** [comment]
Hi Mayank,
We have monitored the remedial task job last 3 days and it was running successfully.
Yesterday i have created a task for the student HardikKumar/Password@2 in UAT and attempt with score less than 33%. Today morning i have checked the Remedial task has been created successfully.

Please check it let me know when we will move it in production.
Please find the screen-shot for your reference.

![image](https://cloud.githubusercontent.com/assets/16384541/15140164/84ee6468-16b7-11e6-90c1-d5bc4e6aa2be.png)

**Comment by mayank2k2** [comment]
So what was exact issue.

Thanks,
Mayank Mishra

**Comment by pankaj44** [comment]
We have checked IIS log as well as application log but we did not find any issue.

**Comment by mayank2k2** [comment]
I completed one task about time for the below user yesterday
check the user: Student 13 A/OUPMath@6141
and no remedial created today.

**Comment by pankaj44** [comment]
I am checking it.

**Comment by pankaj44** [comment]
Mayank,
Can you please check once again i did not find any thing from server log.

**Comment by mayank2k2** [comment]
Pankaj,
Can you create a task and complete homework for your user and share with me.
I will also do the same with my user.

And we will check both the users, whether remedials created or not.

Thanks,
Mayank Mishra

**Comment by pankaj44** [comment]
Hi Mayank,
I have created task and completed it.

![image](https://cloud.githubusercontent.com/assets/16384541/15180039/e281fac8-179c-11e6-8c54-1f806b182a7f.png)

For the user HardikKumar/Password@2

**Comment by pankaj44** [comment]
As discussed,I have deployed batch job application in UAT environment. Could you please create few task in UAT so that we will test it tomorrow.

I have tested in QA environment.Please find the screen-shot for your reference
![image](https://cloud.githubusercontent.com/assets/16384541/15389619/7ba1d7d0-1dd5-11e6-97a4-7096a39b33e7.png)

**Comment by mayank2k2** [comment]
working in UAT

**Comment by mayank2k2** [comment]
issue is fixed in prod so closing
