### ISSUE TITLE
Completed Task not showing in report in same day

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfrodMaths_Prod#12]
I as teacher assigned a task to student on 20th April, student completed the task on same day 20th April.  

![image](https://cloud.githubusercontent.com/assets/16239450/14665023/9db74d7c-06ed-11e6-8e95-014d439176b5.png)

The task is not visible in Teacher's reports--> Task status, student performance doesn't shows the task

![image](https://cloud.githubusercontent.com/assets/16239450/14665085/ffb028e6-06ed-11e6-8b70-8e013098f1fb.png)

**Comment by manasghosh81** [comment]
@mayank2k2 :This should be displayed after the completion of 20th April. Please check this after 20th April 11:59 pm

**Comment by mayank2k2** [comment]
@manasghosh81 we need to see the task status in teacher's report consider a scenario of same day task where teacher want to see the progress at end of day. 
Pleas ediscuss if you have any query.

**Comment by mayank2k2** [comment]
We need this homework/task completion real time data globally and it should not come only after task completion.

**Comment by manasghosh81** [comment]
Code change required as per the Mayank's requirement

**Comment by mayank2k2** [comment]
This is fixed in UAT

**Comment by pankaj44** [comment]
Please check in production and close this issue

**Comment by pankaj44** [comment]
![image](https://cloud.githubusercontent.com/assets/16384541/15009660/6228e428-1205-11e6-9bb6-7ef39fd277c3.png)

**Comment by mayank2k2** [comment]
This is working fine in prod, so closing
