### ISSUE TITLE
wrong password attempt - message

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfrodMaths_Prod#13]
For 5 failed password attempts, we get following message ‘please try after 5 minutes and 0 seconds’.
we can only show 5 minutes and remove seconds 

Also minutes should be minute(s) ans seconds should be second(s)
eg. please try after 5 minute(s)
      please try after 4 minute(s) and 30 second(s)

**Comment by manasghosh81** [comment]
Code change required

**Comment by mayank2k2** [comment]
This not enhancement however its implementation issue

**Comment by mayank2k2** [comment]
This is fixed in UAT

**Comment by pankaj44** [comment]
Please check in production and close this issue

**Comment by pankaj44** [comment]
![image](https://cloud.githubusercontent.com/assets/16384541/15009618/fd6ae2e8-1204-11e6-8f80-3c09d76fbcf0.png)

**Comment by mayank2k2** [comment]
working fine in prod so closing
