### ISSUE TITLE
wrong logo in games

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfrodMaths_Prod#14]
We noticed couple of games are not having ‘oxford maths’ logo but of mymaths.
Could we do a test run again and replace the logos with latest ones?

**Comment by mayank2k2** [comment]
Manas,
Most of the game have logo issue. Below is the sample list that you can refer.

• 3 Dart Finish
• Twenty 4
• Sky Solver Sums to 100
• Sky Solver Multiplying
• Millionaire Easy
• Game 1: Millionaire Easy
And many more you need to check all the games.

Thanks,
Mayank Mishra

**Comment by manasghosh81** [comment]
All the mentioned games are part of the generic list of games issue .We will fix at a glance all this issues since this is part of content issue,not part of application issue

**Comment by sumitmago** [comment]
Hi,
Could you please put down some tentative timelines by which you feel it can be closed? You may want to discuss with Chandan/Subha.

Thanks & Regards
Sumit Mago
Head (Digital Solutions) – Learning & Assessment
Oxford University Press
2nd Floor, Tower-1, Stellar Crest  Business Center, IT Park, C-25 Sector 62,  Noida
(D) - 0120-6718900 Extn - 214, (M) +91-9873299973

The ABC of Innovation:
Conceive
Believe
Achieve

**Comment by sumitmago** [comment]
Hi,
               Few games where we noticed old logo are as mentioned below and attached.

Class No.

Chapter

Games Name

Class 3

Measurements

Millionaire Easy

Class 3

Multiplication

Sky Solver Multiplying

Class 3

Division

Sky Solver Dividing

Class 3

Subtraction

Sky Solver Sums to 100

Class 3

Addition

3 Dart Finish

Class 3

Addition

Twenty 4

Class 4

Addition and Subtraction

Three Darts Finish

Class 4

Addition and Subtraction

Twenty Four

Class 4

Multiplication

Three Darts Finish

Class 4

Measurements

Millionaire Easy

Class 5

Place Value

Billionaire

Class 5

Addition, Subtraction & its Applications

Dart Finish

Class 5

Multiplication, Division and its Application

Twenty 4

Class 5

Decimals

Stepping Stones

Class 5

Measurements

Millionaire Easy

Class 5

Fractions

Fraction Pairs 1

Class 5

Decimals

Decimals Bingo

Class 6

Decimals

Stepping Stones

Class 6

Fractions

Fraction Pairs 1

Class 6

Introduction to Algebra

Algebra Pairs 1

Class 7

Algebraic Expressions

SkySolver Formulae

Class 7

Simple Linear Equations

Equation Pairs

Class 8

Square & Square roots

Square Roots

Class 8

Algebraic Expressions & Identities

Addition and Subtraction of Algebraic Expressions

Class 8

Cubes and Cube Roots

Cubes and Cube Roots

Thanks & Regards
Sumit Mago
Head (Digital Solutions) – Learning & Assessment
Oxford University Press
2nd Floor, Tower-1, Stellar Crest  Business Center, IT Park, C-25 Sector 62,  Noida
(D) - 0120-6718900 Extn - 214, (M) +91-9873299973

The ABC of Innovation:
Conceive
Believe
Achieve

From: MAGO, Sumit
Sent: Thursday, April 21, 2016 5:32 PM
To: 'manasghosh81/OxfrodMaths_Prod'; manasghosh81/OxfrodMaths_Prod
Subject: RE: [manasghosh81/OxfrodMaths_Prod] wrong logo in games (#14)

Hi,
Could you please put down some tentative timelines by which you feel it can be closed? You may want to discuss with Chandan/Subha.

Thanks & Regards
Sumit Mago
Head (Digital Solutions) – Learning & Assessment
Oxford University Press
2nd Floor, Tower-1, Stellar Crest  Business Center, IT Park, C-25 Sector 62,  Noida
(D) - 0120-6718900 Extn - 214, (M) +91-9873299973

The ABC of Innovation:
Conceive
Believe
Achieve

**Comment by pankaj44** [comment]
Could you please check logo issues in UAT.

**Comment by mayank2k2** [comment]
working fine in UAT

**Comment by pankaj44** [comment]
Hi Mayank,
I have moved all the content in production. Could you please check it in production and close it.

**Comment by mayank2k2** [comment]
issues is fixed and now logo are fine in prod environment, so closing the issue.

**Comment by mayank2k2** [comment]
issues is fixed and now logo are fine in prod environment, so closing the issue.
