### ISSUE TITLE
Search functionality issue

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfrodMaths_Prod#15]
[Search function bug.docx](https://github.com/manasghosh81/OxfrodMaths_Prod/files/229471/Search.function.bug.docx)

same issue is in UAT as well.

**Comment by manasghosh81** [comment]
Code change required

**Comment by mayank2k2** [comment]
Working fine in UAT

**Comment by pankaj44** [comment]
Please check in production and close this issue

**Comment by mayank2k2** [comment]
working fine in PROD so closing
