### ISSUE TITLE
Reset School Admin Password

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfrodMaths_Prod#16]
We have observe that in case School Admin has forgotten his password completely and also he is not remember his secret Question and Answer that help to retrieve/reset his password. There is no option from screen for OUP admin to reset password. we need this feature and attached a detailed document.

[Reset School Admin Password.docx](https://github.com/manasghosh81/OxfrodMaths_Prod/files/231601/Reset.School.Admin.Password.docx)

**Comment by pankaj44** [comment]
We have done the changes and deployed it in production.

**Comment by pankaj44** [comment]
![image](https://cloud.githubusercontent.com/assets/16384541/15218671/96e92766-187e-11e6-9721-10e239ee9260.png)

![image](https://cloud.githubusercontent.com/assets/16384541/15218687/ab39327e-187e-11e6-9818-32cec779afab.png)

![image](https://cloud.githubusercontent.com/assets/16384541/15218707/be5cbe0c-187e-11e6-9df1-eb4e5867eedb.png)

**Comment by mayank2k2** [comment]
This is working fine in UAT
if possible can you add key icon

**Comment by pankaj44** [comment]
Enhancement
Resolution -Implement new function  .
verified scenarios in QC or UAT-

![image](https://cloud.githubusercontent.com/assets/16384541/15284141/30768b30-1b6d-11e6-9cf5-0ce9983c8637.png)

![image](https://cloud.githubusercontent.com/assets/16384541/15284147/3e292404-1b6d-11e6-9856-a9bf7c46a1f5.png)

**Comment by pankaj44** [comment]
![image](https://cloud.githubusercontent.com/assets/16384541/15284157/51ee40c8-1b6d-11e6-8219-e02239e392f5.png)

**Comment by mayank2k2** [comment]
working in prod so closing
