### ISSUE TITLE
change password - missing confirmation message 

### ISSUE THREAD

**Issue by sumitmago** [OUPMATH/OxfrodMaths_Prod#17]
hi,
   when we change password for any user on expiry or even otherwise, we should get a confirmatory message that 'Your password is changed successfully. Please re-login with your new password'. we are not getting any confirmation so user may get confused on the status as to weather password is changed or not.

**Comment by manasghosh81** [comment]
@sumitmago :There is a confirm message appearing  after the  change of password from profile page-> change of password.Could you want change the confirmation text as well as  redirect user to login page again.Please confirm.

**Comment by sumitmago** [comment]
Mayank,
               Could you please check and close if it is working?

Thanks & Regards
Sumit Mago
Head (Digital Solutions) – Learning & Assessment
Oxford University Press
2nd Floor, Tower-1, Stellar Crest  Business Center, IT Park, C-25 Sector 62,  Noida
(D) - 0120-6718900 Extn - 214, (M) +91-9873299973

The ABC of Innovation:
Conceive
Believe
Achieve

**Comment by mayank2k2** [comment]
@manasghosh81  we are not getting the confirmation message if we are login first time and system ask to change the password. Please check this scenario.

**Comment by mayank2k2** [comment]
This is bug not enhancement.

**Comment by mayank2k2** [comment]
This is working in UAT

**Comment by pankaj44** [comment]
Please check in production and close this issue

**Comment by mayank2k2** [comment]
Working fine in prod, so closing
