### ISSUE TITLE
Change Password issue - bad user experience

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfrodMaths_Prod#18]
we are getting bad user experience while changing the password.

Step 1: type old password press TAB key
Step 2: type new password press TAB key

we are getting information massage about password however i have put correct password matching the criteria. 

![image](https://cloud.githubusercontent.com/assets/16239450/14739663/b4add734-08a6-11e6-9fb6-1d2185a7a9bf.png)

On save i am able to change/reset the password.

**Comment by manasghosh81** [comment]
@mayank2k2 :Could you please explain this issue little bit more since the issue is not clear to us

**Comment by mayank2k2** [comment]
Please follow the steps On change password:
Step 1: type old password press TAB key
Step 2: type new password press TAB key

we are getting information massage about password however i have put correct password matching the criteria.

**Comment by mayank2k2** [comment]
This issue also happen when you login first time and system ask to change the password, refer the below screen as well.

![image](https://cloud.githubusercontent.com/assets/16239450/14815807/1c1c91e0-0bcb-11e6-9975-f187598e04e8.png)

**Comment by pankaj44** [comment]
![image](https://cloud.githubusercontent.com/assets/16384541/15044144/7f20b4b6-12f0-11e6-9ea6-8b0db862b13b.png)

**Comment by manasghosh81** [comment]
This is fixed in UAT now

**Comment by mayank2k2** [comment]
This is fixed in UAT

**Comment by manasghosh81** [comment]
Root case - usability issue available in production
 Resolution -Require Code changes has been .
verified scenarios in QC or UAT-
Reproduce the steps mentioned above.

**Comment by mayank2k2** [comment]
working in prod
