### ISSUE TITLE
Change school user name from ‘S382_26930’ to ‘school-admin’

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfrodMaths_Prod#19]
We want to shoot one video for Oxford Maths and for that school admin name needs to be easier. So could we change the school admin user name of following school ‘S382_26930’ to ‘school-admin’?

UserName    password
S382_26930  Oxfordmaths@123

**Comment by manasghosh81** [comment]
This issue is fixed.Please check and if it is working as per the requirement ,please close it

**Comment by mayank2k2** [comment]
This is fixed and we are able to login from school-admin / Oxfordmaths@123
