### ISSUE TITLE
Lessons are not opening for student login

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfrodMaths_Prod#20]
![image](https://cloud.githubusercontent.com/assets/16239450/14810258/9dc5a8ec-0baf-11e6-9f4c-2020c603824d.png)

here are few list to check

![image](https://cloud.githubusercontent.com/assets/16239450/14810060/910bc61e-0bae-11e6-8077-3df86d982157.png)

**Comment by mayank2k2** [comment]
please try with user STUDENT331 / OUPMath@111

**Comment by manasghosh81** [comment]
Code change required

**Comment by mayank2k2** [comment]
Still lessons are not opening  eg see lesson 
Comparing Numbers in CHAP 01:Place Value for class 3.

further there have been seen lot of discrepancy between UAT & PROD. those lessons, Homework, game and toolkit are opening fine in  PROD are not opening in UAT.

eg Comparing Numbers in CHAP 01:Place Value for class 3 are opening in PROD but not UAT why???

**Comment by pankaj44** [comment]
Please check in production and close this issue

**Comment by pankaj44** [comment]
I have checked few content in production with the following student login
student33/Password@1 for class 3
student55/Password@1 for class 5

![image](https://cloud.githubusercontent.com/assets/16384541/15009687/9bdee690-1205-11e6-8a6a-3bc2aaf400ca.png)

![image](https://cloud.githubusercontent.com/assets/16384541/15009712/ae13ee6e-1205-11e6-80e2-6b8baab93f5d.png)

**Comment by mayank2k2** [comment]
lessons are opening fine in prod, so closing
note: another issue#27 has been created to deal with content issue for different content in UAT vs PROD
