### ISSUE TITLE
Forgot password - bad user experience

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfrodMaths_Prod#21]
while use forgot password option to retrieve the password:
step1: provide the correct user name 
![image](https://cloud.githubusercontent.com/assets/16239450/14816018/40f36b32-0bcc-11e6-9706-83d81568384f.png)

Step 2: Press TAB key
below message appears
![image](https://cloud.githubusercontent.com/assets/16239450/14816048/6321dce8-0bcc-11e6-8655-f65745a7a1f9.png)

The message should not appear if we put the correct username, focus should go to continue button.
if we are putting the incorrect user name then message should appear and alignment should be on the right side.

Step 3: press continue button
step 4: provide the secret Answer and press TAB key
Below message appears.

![image](https://cloud.githubusercontent.com/assets/16239450/14815550/a6f3f472-0bc9-11e6-86dd-13127b737b14.png)

The message should not appear, focus should go to continue button.

**Comment by manasghosh81** [comment]
Code change Required

**Comment by manasghosh81** [comment]
This issue is fixed now in UAT

**Comment by mayank2k2** [comment]
This is fixed in UAT

**Comment by pankaj44** [comment]
Root case - Change of original implementation.
 Resolution - Done the code changes for Tab key press.
 Verified scenarios in UAT.

![image](https://cloud.githubusercontent.com/assets/16384541/15077741/7f2f04c0-13cd-11e6-86c8-f7b59ab519f0.png)

![image](https://cloud.githubusercontent.com/assets/16384541/15077755/8f331e10-13cd-11e6-912d-85fc91a6e7a3.png)

**Comment by mayank2k2** [comment]
working in prod
