### ISSUE TITLE
Old vs New Password check not happening

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfrodMaths_Prod#22]
There is no check while resetting password from profile or we are login fist time when it ask for new password.
same old password can be enter as new password and system accept it.
New password should not be same as old password. 
This validation is totally missing.

**Comment by pankaj44** [comment]
![image](https://cloud.githubusercontent.com/assets/16384541/15044187/ca3d69b2-12f0-11e6-9ea5-c6c4c1de546d.png)

**Comment by mayank2k2** [comment]
Issues is fixed in UAT

**Comment by pankaj44** [comment]
Root case - Change of original implementation
 Resolution - Implement the validation of new and old password.

 verified scenarios in QC or UAT-
 Screen-shot is attached below from UAT

![image](https://cloud.githubusercontent.com/assets/16384541/15077543/9ab8c998-13cc-11e6-8a0c-fdccf4c05fbe.png)

**Comment by mayank2k2** [comment]
working fine in prod
