### ISSUE TITLE
UAT: change UAT Url and point to http://www.uat.oxfordmaths.co.in/

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfrodMaths_Prod#24]
Change UAT url http://oup-mymath-elb-2074067178.ap-southeast-1.elb.amazonaws.com
to http://www.uat.oxfordmaths.co.in/ in all the places it still refer the old long url

Refer the below  mail on new school registration:

Dear Student1 1,
Welcome and thank you for registering for Oxford Maths.
You can now sign in at http://oup-mymath-elb-2074067178.ap-southeast-1.elb.amazonaws.com with your username and temporary password mentioned below. You need to change the password after signing in.
Username: Student11
Password: OUPMath@572
Your password is secret and is known only by you.
If you have any questions, please speak to your teacher or administrator or email Customer Support at oxfordmathsindia@oup.com.
Best wishes,
Oxford Maths Team

**Comment by manasghosh81** [comment]
This will be done tomorrow(3/5/2016) as discussed on our weekly issue discussion.

**Comment by manasghosh81** [comment]
This issue has been fixed.Please check .If everything works as per the requirement,Please close it

**Comment by mayank2k2** [comment]
@manasghosh81 can you let me know what all different  area you have verifies.

**Comment by manasghosh81** [comment]
we config hostname
URL rewrite
pingu.html

**Comment by mayank2k2** [comment]
@manasghosh81 my question is what all area you verified in UAT env for the fix.

**Comment by mayank2k2** [comment]
If you have verified then  why i still see issue on welcome letter there is no hostname

Dear mayank mishra,
Your email address has been used to register an account on Oxford Maths
You have been registered in: Mayank School may 2016
Your role is: School Administrator
To start using your account, please sign in at [hostName] with your username and temporary password mentioned below. You need to change the password after signing in.
Username: S45_3956
Password: OUPMath@852
If you have any questions, please email Customer Support at oxfordmathsindia@oup.com.
Best wishes,

**Comment by manasghosh81** [comment]
@mayank2k2 :Please check the mail that I have forward to you.

**Comment by mayank2k2** [comment]
@manasghosh81 issues still exist i send 2 emails yesterday

**Comment by manasghosh81** [comment]
@mayank2k2 :I think this issue is resolved now after fixing the issue # 28

**Comment by mayank2k2** [comment]
Issues is fixed in UAT

Dear mayank mishra,
Your email address has been used to register an account on Oxford Maths
You have been registered in: Mayank School may 2016
Your role is: School Administrator
To start using your account, please sign in at http://www.uat.oxfordmaths.co.in with your username and temporary password mentioned below. You need to change the password after signing in.
Username: S45_3956
Password: OUPMath@852
If you have any questions, please email Customer Support at oxfordmathsindia@oup.com.
Best wishes,
Oxford Maths Team
Customer Support
Oxford University Press

**Comment by manasghosh81** [comment]
@mayank2k2 :Since this issue is fixed ,Please close it.

This is a change request to make the URL redirection for uat domain using WWW.

The changes has been reflected for content  opening, email send to school admin,resend email to school admin after search  school,welcome letter.

**Comment by mayank2k2** [comment]
fix is working on UAT
