### ISSUE TITLE
UAT: Upload Action keep processing for 30 students

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfrodMaths_Prod#26]
similar issue : https://github.com/OUPMATH/OxfordMath_UAT/issues/9

Today i uploaded 30 student for new school i have created and it is taking more than 5 minutes and processing still continue.
see the screen shot

![image](https://cloud.githubusercontent.com/assets/16239450/14949408/6a45bce8-1067-11e6-88f8-3bccbcd2ae40.png)

still continue processing after 10 minutes:
![image](https://cloud.githubusercontent.com/assets/16239450/14949418/7790c866-1067-11e6-9c99-7404e7f84c54.png)

only 3 student uploaded where are rest student ???
![image](https://cloud.githubusercontent.com/assets/16239450/14949432/8b3a913a-1067-11e6-87e7-084b4b24fc5a.png)

**Comment by mayank2k2** [comment]
The priority will change to higher if the issue is also in PROD.

**Comment by pankaj44** [comment]
Hi Mayank,
I have done the modification in code side and deployed it in UAT. Could you please check it and let me know.

**Comment by mayank2k2** [comment]
This is working in UAT now

**Comment by pankaj44** [comment]
Production deployment has been completed.Could you please check it and close the defect.

**Comment by sumitmago** [comment]
Hi,
Could I request editorial team to please check and close all working items?

Thanks & Regards
Sumit Mago
Head (Digital Solutions) – Learning & Assessment
Oxford University Press
2nd Floor, Tower-1, Stellar Crest  Business Center, IT Park, C-25 Sector 62,  Noida
(D) - 0120-6718900 Extn - 214, (M) +91-9873299973

The ABC of Innovation:
Conceive
Believe
Achieve

**Comment by mayank2k2** [comment]
This is working in prod, so closing the issue

**Comment by sumitmago** [comment]
Can we please do this on priority….I am getting requests from OXED to share login ids and I don’t want them to see errors in this

Thanks
Pawan

From: MAGO, Sumit
Sent: Monday, May 30, 2016 3:19 PM
To: OUPMATH/OxfrodMaths_Prod; OUPMATH/OxfrodMaths_Prod
Cc: ADHIKARI, Pawan
Subject: RE: [OUPMATH/OxfrodMaths_Prod] UAT: Upload Action keep processing for 30 students (#26)

Hi,
Could I request editorial team to please check and close all working items?

Thanks & Regards
Sumit Mago
Head (Digital Solutions) – Learning & Assessment
Oxford University Press
2nd Floor, Tower-1, Stellar Crest  Business Center, IT Park, C-25 Sector 62,  Noida
(D) - 0120-6718900 Extn - 214, (M) +91-9873299973

The ABC of Innovation:
Conceive
Believe
Achieve
