### ISSUE TITLE
welcome letter generation for a complete class

### ISSUE THREAD

**Issue by sumitmago** [OUPMATH/OxfrodMaths_Prod#3]
hi, 
  as discussed we would appreciate a link to generate complete plf file with 'welcome letter' of a class. OUP admin and School Admin should be able to performthis function. Please take a snapshot of current screen, add this link and send it back for sign off before you start the development.

**Comment by sumitmago** [comment]
hi, what is the plan on this? By when we thinking of closing this?

**Comment by sumitmago** [comment]
assigning to Manas

**Comment by manasghosh81** [comment]
This required code change.

**Comment by mayank2k2** [comment]
working in UAT

**Comment by manasghosh81** [comment]
This changes is now available in Prod.
Root case - New change request.
Resolution - Functionality implemented
verified scenarios in UAT-
Generate welcome letter with more than 5 records

**Comment by mayank2k2** [comment]
working fine in prod
