### ISSUE TITLE
SSL certificate for mymaths

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfrodMaths_Prod#30]
SSL certificate need to install and change other configurations in application point to https:// instead of 
http://

Please discuss with Jitendra / me for the downtime required.

**Comment by mayank2k2** [comment]
@manasghosh81 I have changes its priority from P2 to P1 as we going to do to penetration test. please fix the issue.

**Comment by pankaj44** [comment]
Hi Mayank,
We need to discuss with you on this issue. After that we will be going to do any changes.

**Comment by pankaj44** [comment]
Hi Mayank,
Could you please check now?

**Comment by mayank2k2** [comment]
working in production.
