### ISSUE TITLE
Read/Unread envelop icons are wrongly display Read/Unread Notifications

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfrodMaths_Prod#31]
Read/Unread Notification icons are showing wrong icons.
Open envelop icon should be for already Read notification and tool-tip should be Mark Unread 
and close envelop should be for unread or new notification and tool-tip should be Mark Read. 
Please see below

![image](https://cloud.githubusercontent.com/assets/16239450/15104027/ef144274-15cf-11e6-974b-b36d7f631798.png)

![image](https://cloud.githubusercontent.com/assets/16239450/15104114/01914162-15d1-11e6-9a11-6a0c7b2686ad.png)

**Comment by manasghosh81** [comment]
@mayank,
Image needs to be swapped.

**Comment by pankaj44** [comment]
We have done the changes and deployed it in production.

**Comment by pankaj44** [comment]
![image](https://cloud.githubusercontent.com/assets/16384541/15218816/29ef0d50-187f-11e6-81c4-45c40121c888.png)

**Comment by mayank** [comment]
Hi everyone,  sorry but I am not the right guy you have tagged in this
thread. You may be looking for someone else,  but If this is an open source
project I am more than happy to help.

**Comment by mayank2k2** [comment]
This is working fine in UAT

**Comment by pankaj44** [comment]
Root case - Change of original implementation.
Resolution - Done the code changes.
Verified scenarios in Prod.

![image](https://cloud.githubusercontent.com/assets/16384541/15284078/ba3991c4-1b6c-11e6-9349-977157f053bc.png)

**Comment by mayank2k2** [comment]
working in prod so closing
