### ISSUE TITLE
Oxford Maths Cookie Audit

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfrodMaths_Prod#32]
Hi Manas /Pankaj,
Edwin has shared the email in Feb regarding list of cookies are using in Oxford Math.
Please populate the cookies audit form and send back to us.   

Thanks,
Mayank Mishra

[Cookie_audit_form.xlsx](https://github.com/manasghosh81/OxfrodMaths_Prod/files/256393/Cookie_audit_form.xlsx)

[International Production Deployment instructions 2.0.docx](https://github.com/manasghosh81/OxfrodMaths_Prod/files/256386/International.Production.Deployment.instructions.2.0.docx)

**Comment by manasghosh81** [comment]
we will consolidate all the cookies used in this application along with it's purpose

**Comment by manasghosh81** [comment]
Please find the attached  cookie list used om OM application
[Cookie_audit_form_OM.xlsx](https://github.com/manasghosh81/OxfrodMaths_Prod/files/274641/Cookie_audit_form_OM.xlsx)

Please review it and close this issue if everything are ok

**Comment by mayank2k2** [comment]
@pankaj44 , below are total 6 cookies and you mention only 5 , can you add the information about missing one.  

![image](https://cloud.githubusercontent.com/assets/16239450/15461741/f567ed68-20da-11e6-999b-e0ec727d2aff.png)

**Comment by manasghosh81** [comment]
Updated the cookielist
[Cookie_audit_form_OM v.1.0.xlsx](https://github.com/OUPMATH/OxfrodMaths_Prod/files/277519/Cookie_audit_form_OM.v.1.0.xlsx)

**Comment by manasghosh81** [comment]
Please  close this issue if everything is OK
