### ISSUE TITLE
Wrong links on FAQ page

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfrodMaths_Prod#33]
![image](https://cloud.githubusercontent.com/assets/16239450/15347095/e5f204ca-1cdb-11e6-956f-d025c240f663.png)

![image](https://cloud.githubusercontent.com/assets/16239450/15347100/f32bff9c-1cdb-11e6-95b9-f8d7cb73c2c4.png)

**Comment by pankaj44** [comment]
Could you please check now?

**Comment by mayank2k2** [comment]
working fine
