### ISSUE TITLE
Teacher Class Performance Report

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfrodMaths_Prod#34]
@manasghosh81  this issues was discussed a long back during UAT (with soma, subha and sumit) and it was decided to fix this during support period. All the data should be print rather that print screen shot. I am logging this issue so that we can track.

also below issue is pending as well 
https://github.com/OUPMATH/OxfordMath_UAT/issues/136

can you discuss and put any tentative timeline.

**Comment by manasghosh81** [comment]
Not able to trace which defect you want to mention here.

**Comment by mayank2k2** [comment]
@manasghosh81 , @pankaj44 below are the report formats we have design, we are still working on student performance report format.

**Class performance**
[Chapter-wise Score Report.docx](https://github.com/manasghosh81/OxfrodMaths_Prod/files/271919/Chapter-wise.Score.Report.docx)
[Student Performance Comparison Report.docx](https://github.com/manasghosh81/OxfrodMaths_Prod/files/271920/Student.Performance.Comparison.Report.docx)
[Task-wise Score Report.docx](https://github.com/manasghosh81/OxfrodMaths_Prod/files/271921/Task-wise.Score.Report.docx)

**Task Status**
[Student-wise Task Completion Status.docx](https://github.com/manasghosh81/OxfrodMaths_Prod/files/271923/Student-wise.Task.Completion.Status.docx)
[Task Status Report.docx](https://github.com/manasghosh81/OxfrodMaths_Prod/files/271922/Task.Status.Report.docx)

**Comment by mayank2k2** [comment]
by mistake it closes

**Comment by mayank2k2** [comment]
@pankaj44 pleas discuss with me before start work on this.

**Comment by mayank2k2** [comment]
@pankaj44 , Please update me on this
Thanks, mayank.

**Comment by pankaj44** [comment]
I have deployed it in UAT. Could you please check and let me know.

**Comment by mayank2k2** [comment]
Report is not currently fix and showing below screen when click on print

![image](https://cloud.githubusercontent.com/assets/16239450/17322098/6edc7518-58b9-11e6-8ecc-5339b0076f66.png)

![image](https://cloud.githubusercontent.com/assets/16239450/17322075/5908c28c-58b9-11e6-8eee-e2137e399683.png)

**Comment by pankaj44** [comment]
I am looking into it.

**Comment by pankaj44** [comment]
Hi mayank,
Can you please check now.

**Comment by mayank2k2** [comment]
now it is working

**Comment by pankaj44** [comment]
Hi Mayank,
I have moved this changes in UAT. Could you please check it and let me know.

**Comment by mayank2k2** [comment]
Reports are working fine in UAT, Please deploy the changes in prod.

**Comment by pankaj44** [comment]
Hi Mayank,
I have moved the changes in production.Could you please check and close the defect.

**Comment by mayank2k2** [comment]
working fine in production so closing
