### ISSUE TITLE
OM Left slider Menu

### ISSUE THREAD

**Issue by sumitmago** [OUPMATH/OxfrodMaths_Prod#36]
Hi, 
    We are getting strong customer feedback that left slider menu does not catches eye of a new user and it remain un-noticed. I recall during designing discussions too, we wanted a design or some kind of a blinker that catches immediate attention of even a new fresh user

![left menu](https://cloud.githubusercontent.com/assets/13584396/15465519/86e9f224-20f2-11e6-8272-b927fdf247b5.PNG)
.

**Comment by manasghosh81** [comment]
Based on discussion with @mayank2k2 ,TCS support team will update issue with suggested changes.THEN OUPI will confirm the requirement

**Comment by manasghosh81** [comment]
@mayank2k2 ,@sumitmago
Please review the scenarios in attached document.
[Left menu navigation by user in OM application.docx](https://github.com/OUPMATH/OxfrodMaths_Prod/files/279143/Left.menu.navigation.by.user.in.OM.application.docx)

**Comment by mayank2k2** [comment]
@sumitmago , @manasghosh81 This looks good to me.

**Comment by pankaj44** [comment]
Hi Mayank,
I have implemented this changes only for student in UAT. Could you please check it and let me know if it is fine then we will implement it for other role also.

**Comment by mayank2k2** [comment]
yes its fine

**Comment by mayank2k2** [comment]
@pankaj44  I discuss this sumit and other member here, and it was decided earlier with subha to hide this navigation bar due to small devices.
so can we have UI design for this icon that can eye catch up/ noticeable for users those are new. 

Please send the 2-3 UI design. 

Thanks, mayank

**Comment by pankaj44** [comment]
Production deployment has been completed.

**Comment by mayank2k2** [comment]
Issue is fixed in prod so closing.
