### ISSUE TITLE
Asset not loading-G3,Ch7

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfrodMaths_Prod#38]
Following asset is not loading now.

![image](https://cloud.githubusercontent.com/assets/16831643/15500450/63df89c2-21c6-11e6-9adb-3430f0ebd5dd.png)

Please check.

**Comment by pankaj44** [comment]
@kirti-sharma 
I am able to open this content after 4-5 minutes.Please let me know what is loading time in offline player.

**Comment by kirti-sharma** [comment]
Now opening in 10 seconds in production.
