### ISSUE TITLE
Unable to access Homework and Lessons in Production Environment

### ISSUE THREAD

**Issue by nehasehgal** [OUPMATH/OxfrodMaths_Prod#39]
[issues.docx](https://github.com/OUPMATH/OxfrodMaths_Prod/files/283759/issues.docx)

**Comment by manasghosh81** [comment]
There is some code issue that  is why the content which are assigning as  task those task must contain different files format flash and xml .We have fixed this issue .This will be deployed production on 27/3

**Comment by manasghosh81** [comment]
Please check this UAT only till we deploy this code changes in Prod

**Comment by mayank2k2** [comment]
@manasghosh81 , @pankaj44 
Manas/Pankaj,
Can you update what was issue and why this broken working OH & Lesson in prod. 

Thanks,
Mayank Mishra

**Comment by pankaj44** [comment]
Hi Neha,
Could you please check it and let me know if you have any queries.

**Comment by nehasehgal** [comment]
Hi,

No, it is working  now. I am closing the issue. 

Neha
