### ISSUE TITLE
Task Report - Score display

### ISSUE THREAD

**Issue by sumitmago** [OUPMATH/OxfrodMaths_Prod#4]
hi,
   basis the demo given to management, we have got a feedback that class report and other reports should show results of tasks even if task is not over. so the marks of the task should get reflected in the reports as and when task are submitted (without waiting for task expiry date to reach). you may create the FSD for this change and send it back for approval to start work.

**Comment by sumitmago** [comment]
hi, what is the plan on this? By when we thinking of closing this?

**Comment by sumitmago** [comment]
Assigning to Manas

**Comment by manasghosh81** [comment]
Hi Mayank,
Please check this issue.I have deployed it in UAT because it involves the business also.Please check and validates  your business team also

Thanks,
Manas

**Comment by mayank2k2** [comment]
working in UAT

**Comment by mayank2k2** [comment]
working in UAT

**Comment by pankaj44** [comment]
Enhancement
Implement new function.

**Comment by mayank2k2** [comment]
working in prod so closing
