### ISSUE TITLE
typing oxfordmaths.co.in and hit enter issue

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfrodMaths_Prod#41]
if we type oxfordmaths.co.in in the url and hit enter it should automatically redirect to https://www.oxfordmaths.co.in

currently it is not doing so and displaying below error, lots of customer are getting this issue we need the fix ASAP.

![image](https://cloud.githubusercontent.com/assets/16239450/15600500/e6c41e6e-2407-11e6-87bd-171a18bc3f58.png)

**Comment by manasghosh81** [comment]
oxfordmath.co.in->http://www.oxfordmaths.co.in redirection issue is fixed.

**Comment by mayank2k2** [comment]
Not fixed correctly
if we type oxfordmaths.co.in in the url and hit enter it should automatically redirect to https://www.oxfordmaths.co.in

**Comment by mayank2k2** [comment]
After clearing the browser history, it is working

**Comment by mayank2k2** [comment]
http://www.oxfordmaths.co.in is not redirecting to https://www.oxfordmaths.co.in automatically

**Comment by manasghosh81** [comment]
Please check and close it

**Comment by mayank2k2** [comment]
now working fine in prod
