### ISSUE TITLE
Wrong url pointing to welcome letter and other places

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfrodMaths_Prod#42]
This was fixed in issue#24,
but i don't know how this is broken again can you guys check why this is broken.
everywhere it points to **http://** whereas it should be **https://** in welcome letters.

**Comment by pankaj44** [comment]
Hi Mayank,
Could you please check now.

**Comment by mayank2k2** [comment]
@pankaj44 have you check these, what all places you verify and what was issue? we discuss earlier before marking fix you need to write proper comment

**Comment by pankaj44** [comment]
During the deployment old config file was not replace with new config. Hence issue comes. I have modified the config file and checked welcome letter and reset school admin password both are working fine.

**Comment by mayank2k2** [comment]
working fine in prod
