### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfrodMaths_Prod#43]
Hi,
   Login error was coming sometime back. could you please check.   I would appreciate detailed explanation along with reasons.
![error](https://cloud.githubusercontent.com/assets/16239450/15697181/5f66d8cc-27d5-11e6-8cd0-d32acc1b3fe0.png)

**Comment by pankaj44** [comment]
I am working into it.

**Comment by manasghosh81** [comment]
Please close this issue since this is an infrastructure issue due to below changes.
The rewrite rule at web server was written perfectly. The ELB setup had 2 problems
- No time limit defined for stickiness
- 80 to 443 along same certificate chain was missing

**Comment by mayank2k2** [comment]
now working fine in prod
