### ISSUE TITLE
Unable to print Student's Performance Report

### ISSUE THREAD

**Issue by nehasehgal** [OUPMATH/OxfrodMaths_Prod#44]
Hi Manas,

We are unable to take the print out of Student Performance report from student as well as teacher's ID. Please check and revert.

Thanks!!
Neha

**Comment by pankaj44** [comment]
Hi Neha,
Could you please share the teacher and student credential.

**Comment by nehasehgal** [comment]
Hi,

Student ID - Samarjeetsingh3 Password - OUPMath@429
Teacher ID - SUMITMAGO1  Password - Sumitmago@1

Regards,
Neha

**Comment by nehasehgal** [comment]
Gentle reminder.

**Comment by pankaj44** [comment]
Hi Neha,
I have checked in production environment with the credential provided by you. It is working fine . Please find the downloaded report.

[PerformanceReport_Samarjeetsingh3.pdf](https://github.com/OUPMATH/OxfrodMaths_Prod/files/313368/PerformanceReport_Samarjeetsingh3.pdf)

Could you please check it at your end and let me know if you have any queries.

**Comment by nehasehgal** [comment]
Hi Pankaj,

I am still unable to get the print out (hard copy) of Student Performance Report. Can you please check and revert. 

Neha

**Comment by pankaj44** [comment]
Hi Neha,
Could you please share your email address.

**Comment by nehasehgal** [comment]
Hi,

It's neha.sehgal@oup.com

**Comment by nehasehgal** [comment]
Hi Pankaj,

As discussed, we are able to take the print out in Chrome but not in Internet Explorer.  Please check and revert.

Neha

**Comment by nehasehgal** [comment]
Hi, it is neha.sehgal@oup.commailto:neha.sehgal@oup.com

Regards,
Neha Sehgal
Executive (Sales Support) – Learning & Assessment
Oxford University Press
2nd Floor, Tower-1, Stellar Crest  Business Center, IT Park, C-25 Sector 62,  Noida
(D) - 0120-4040900 Extn - 253, (M) +91-9990659730

**Comment by pankaj44** [comment]
Hi Neha,
I have fixed this defect. Could you please check it in all browser(IE,Chrome,Mozilla). If is is working fine than close the defect.

**Comment by nehasehgal** [comment]
issue fixed.
