### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfrodMaths_Prod#45]
In the OH of , G7_Ch 14_Construction of triangles, marks were getting assigned without answering in Q2.
![image](https://cloud.githubusercontent.com/assets/16831643/16411760/54ce42f2-3d46-11e6-8856-336b2d2c6c22.png)

**But now we are not able to reproduce this error.**
As I clear cache regularly every hour while checking OM, it should not be the reason behind this inconsistency. 

Please look into this matter.

**Comment by kirti-sharma** [comment]
I was able to reproduce the error today also (refer screenshot).
![image](https://cloud.githubusercontent.com/assets/16831643/16446132/bb1c0df6-3e03-11e6-90ca-c5123c9e4ad9.png)

Apparently, it is occurring only in this case of random options.

**Comment by mayank2k2** [comment]
Pankaj,
Can you call me.

Thanks,
Mayank Mishra

**Comment by pankaj44** [comment]
If the angle value is showing some value in that case error is not appears but if angle value is null in that case issue will appears.

**Null angle value** 

![image](https://cloud.githubusercontent.com/assets/16384541/16447946/91863918-3e0c-11e6-84aa-fe2276497222.png)

**Some angle value** 

![image](https://cloud.githubusercontent.com/assets/16384541/16447959/a2f5d848-3e0c-11e6-8090-1244e2723c6f.png)

**Comment by pankaj44** [comment]
Content has been moved in UAT. Could you please check it in UAT and let me know your feedback. If every thing is fine then I will move this content in Production.

**Comment by mayank2k2** [comment]
@kirti-sharma , can you check this.

**Comment by kirti-sharma** [comment]
It is working fine in UAT. Please move to production.

**Comment by pankaj44** [comment]
I have moved the content in Production could you please check it and close the defect.

**Comment by kirti-sharma** [comment]
Issue resolved in production.
