### ISSUE TITLE
Profile icon doesn't contain image

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfrodMaths_Prod#46]
![image](https://cloud.githubusercontent.com/assets/16239450/16756929/26a28470-4826-11e6-9fcd-8a2686c8fc22.png)

![image](https://cloud.githubusercontent.com/assets/16239450/16757028/f6b290c4-4826-11e6-996f-a9c5b989f16d.png)

**Comment by pankaj44** [comment]
I am looking into it.

**Comment by mayank2k2** [comment]
any update on this issue.

**Comment by pankaj44** [comment]
Hi Mayank,
I have done the changes and deployed it in UAT. Could you please check and let me know the feedback.

**Comment by mayank2k2** [comment]
working fine in UAT

**Comment by mayank2k2** [comment]
please move the changes into production

**Comment by mayank2k2** [comment]
there is issue if i go to OUPADMIN/school admin and search and view any teacher / student profile the top profile icon changes, that is wrong implementation caught today in UAT.

**Comment by pankaj44** [comment]
Could you please clear the cache and try it. If you still face the issue please let me know.

**Comment by mayank2k2** [comment]
![image](https://cloud.githubusercontent.com/assets/16239450/17099780/01b40d16-5288-11e6-8146-b538b1ac4248.png)

![image](https://cloud.githubusercontent.com/assets/16239450/17099744/d0a08150-5287-11e6-812e-95c5337f6cb5.png)

![image](https://cloud.githubusercontent.com/assets/16239450/17099760/ea6a6506-5287-11e6-88a5-6b25027c1095.png)

**Comment by pankaj44** [comment]
Hi Mayank,
I have checked it from my end it is working fine. Please find the screen-shot for your reference

![image](https://cloud.githubusercontent.com/assets/16384541/17100975/666d95cc-528f-11e6-9648-add8eb94a318.png)

**Comment by mayank2k2** [comment]
now working fine in UAT

**Comment by mayank2k2** [comment]
working fine in Prod

**Comment by mayank2k2** [comment]
working fine in Prod
