### ISSUE TITLE
Able to attempt assigned task more than three times

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfrodMaths_Prod#47]
In the following three assets, by clicking 'Next' on the checkout page, the student is able to attempt the assigned task unlimited times:

**G Chapter                                                      Topic                                                                     Type**
4   Chapter 8 Fractions                                      Equivalent Fractions                                               OH
4   Chapter 12 Time                                      Reading Time to Exact Minute                               OH
7   Chapter 9 Percentage and its Applications  Conversion of Fraction, Decimal and Percentage   OH

Please limit the number of maximum attempts to 3.

**Comment by pankaj44** [comment]
Hi Kiriti,
I have checked the content. You are referring the next button inside content. Please find the screen-shot for your reference
![image](https://cloud.githubusercontent.com/assets/16384541/16763953/0eed759c-4849-11e6-8d37-81e2974c23e2.png)

Please correct me if I am wrong.

**Comment by kirti-sharma** [comment]
Yes, this is the Next button on the checkout page.

**Comment by pankaj44** [comment]
Thanks for confirmation. We will look into it and will let you know once it will fixed.

**Comment by pankaj44** [comment]
Hi Kirti,
Corrected contents have been moved for all Grade in UAT/Production. Could you please check it and close the defect.

**Comment by kirti-sharma** [comment]
Hi Pankaj, 
This issue is resolved in production.
