### ISSUE TITLE
Edit view on Create and Send Notifications show wrong Recipients

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfrodMaths_Prod#48]
use credential in UAT : S55_4095/Oupmath@2016

figure 1: select 1st record that is student (only student is selected)
![image](https://cloud.githubusercontent.com/assets/16239450/17097438/6fee6f72-527b-11e6-8cae-a513d2431cbd.png)

figure 2: select 2st record that is teacher (**issue: both  teacher & student are selected)**
![image](https://cloud.githubusercontent.com/assets/16239450/17097479/9ad62068-527b-11e6-8895-201151f77d84.png)

now refresh and select 2 record only that is teacher (only teacher is selected)
![image](https://cloud.githubusercontent.com/assets/16239450/17097519/be336fc0-527b-11e6-9ae0-54da47ec4a78.png)

**Comment by pankaj44** [comment]
I am looking into it.

**Comment by pankaj44** [comment]
I have fixed the problem in UAT. Could you please check and let me know if you have any queries.

**Comment by mayank2k2** [comment]
working fine in UAT

**Comment by mayank2k2** [comment]
working fine in Prod
