### ISSUE TITLE
Basic search showing wrong parameter after second search

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfrodMaths_Prod#49]
1 Login with OUPADMIN
use basic search for anuj/garg
![image](https://cloud.githubusercontent.com/assets/16239450/17128574/491c6344-532b-11e6-85e8-4e9ac54dde4b.png)

go to edit and view profile
![image](https://cloud.githubusercontent.com/assets/16239450/17128597/8a1da40c-532b-11e6-90eb-b5ef3adfba98.png)

now use basic search for aanchal/verma and search
![image](https://cloud.githubusercontent.com/assets/16239450/17128603/9b55f5d0-532b-11e6-8617-99ec400d4c54.png)

**it shows the old search parameter an result (not the new parameter and result)**
![image](https://cloud.githubusercontent.com/assets/16239450/17128616/b39456d2-532b-11e6-8af7-d82aee561d61.png)

**Comment by pankaj44** [comment]
I am looking into it.

**Comment by pankaj44** [comment]
Hi Mayank,
I have moved this changes in UAT. Could you please check it and let me know.

**Comment by mayank2k2** [comment]
This is working fine in UAT

**Comment by mayank2k2** [comment]
please deploy in prod

**Comment by pankaj44** [comment]
Hi Mayank,
Production deployment has been completed. Could you please check close the defect.

**Comment by mayank2k2** [comment]
working fine in production , so closing it
