### ISSUE TITLE
Notification history not showing for OUPADMIN

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfrodMaths_Prod#50]
if we create new notification from OUPADMIN, no notification history showing. it always say no data found.

![image](https://cloud.githubusercontent.com/assets/16239450/17133771/28fc0514-5345-11e6-91c1-454a039b68eb.png)

**Comment by pankaj44** [comment]
Could you please check now.

**Comment by mayank2k2** [comment]
now it is working fine in UAT

**Comment by mayank2k2** [comment]
Working fine in Prod
