### ISSUE TITLE
School admin login-Class not changing when notification is sent to different classes

### ISSUE THREAD

**Issue by madhumitadey** [OUPMATH/OxfrodMaths_Prod#51]
1. Login using School admin credentials.
2. Go to create notification.
3. Create notification for any class except 3. Here notification has been created for Class 4.

![image](https://cloud.githubusercontent.com/assets/16831474/17322956/99886a5c-58bd-11e6-97f2-550a68793a8c.png)

Problem encountered: Under the notification history, the class displayed is always Class 3 (note that the notification was created for Grade 4).  On editing/viewing the notification, the wrong class is displayed.
![image](https://cloud.githubusercontent.com/assets/16831474/17322969/a8cf396e-58bd-11e6-9ca1-a4cf0d9eedd8.png)

**Comment by pankaj44** [comment]
Hi Madhumita,
I have checked the above defect in UAT. It is working fine. Please find the screen-shot for your reference

![image](https://cloud.githubusercontent.com/assets/16384541/17768861/bdb75800-6553-11e6-8596-ee14cc0382ec.png)

![image](https://cloud.githubusercontent.com/assets/16384541/17768886/d99f208e-6553-11e6-9eb1-998cefb142a0.png)

Could you please test it in different school and let me know the output.

**Comment by madhumitadey** [comment]
The issues has been resolved when notification is sent to students.
- But the problem exists when the notification is sent to a teacher. Please see screenshot below.

![image](https://cloud.githubusercontent.com/assets/16831474/17798868/2b79173a-65f3-11e6-9ba9-0d86418caf32.png)

![image](https://cloud.githubusercontent.com/assets/16831474/17798919/8bfa1e06-65f3-11e6-9e54-9349245ef33b.png)

I have tested it on the production site. Should I try this in UAT environment?

**Comment by pankaj44** [comment]
Hi Madhumita,
 Could you please check it for different school.

**Comment by madhumitadey** [comment]
Okay.

**Comment by pankaj44** [comment]
Please check in UAT and let me know.

**Comment by madhumitadey** [comment]
This is not working on UAT as well. I tried sending a notification to a Grade 4 teacher. 
![image](https://cloud.githubusercontent.com/assets/16831474/17918360/cdd1564a-69e1-11e6-8dab-2b4e9fa1b771.png)

![image](https://cloud.githubusercontent.com/assets/16831474/17918363/d42e07c2-69e1-11e6-9101-df8a1462c1b3.png)

**Comment by pankaj44** [comment]
Hi Madhumita,
Could you please share the school admin credentials from UAT.I will check and let you know.

**Comment by madhumitadey** [comment]
Hi Pankaj,
The credentials are:

Username: S3_5
Password: OUPMath@363

However, I just tried checking it for a new school on UAT, it is working fine there.

**Comment by pankaj44** [comment]
Hi Madhumita,
Above credential is not working. Could you please re-check and let me know the correct credential.
I am checking it in UAT.

**Comment by madhumitadey** [comment]
I have reset the password. Please try with the following credentials.
Username: S3_5
Password: OUPMath@568

**Comment by pankaj44** [comment]
Hi Madhumita,
I have investigated the issue and found that single teacher is associate with multiple class and section. Hence if you create a notification for class 4 in notification history you are able to see the class 3. 

Please let me know if you have any queries.

**Comment by madhumitadey** [comment]
@mayank2k2 Please check and suggest.

**Comment by mayank2k2** [comment]
Pankaj, this  is wrong implementation.
if we create notification for class 4& section D, it should be for crated for same class 4& section D.
how it is showing different  class & section.

**Comment by pankaj44** [comment]
Hi Mayank,
Suppose a teacher is assign to a class 4 and Section D also he is assign for a class 3 and section C. If you are creating a notification for class 4 and section D then that will be applicable for class 3 and section C also because same teacher is associate with both the class and section.

technical side.
We are not mapping a notification to class or section. Currently the implementation is like
If you create a notification for a particular teacher then it will go for all class and sections.

**Comment by mayank2k2** [comment]
we need to fix the issue as expected

**Comment by pankaj44** [comment]
Hi Mayank/Madhumita,
I have done the changes and deployed it in UAT. Could you please check and let me know your feedback.

Example:- If teacher is associate with more than one class and section then only those class section will be visible in notification history those you are creating.

**Comment by madhumitadey** [comment]
Looks good to me. Kindly notify when the changes will be made in production. Will check and close the issue.

**Comment by pankaj44** [comment]
Production deployment has been completed. Could you please check it and close the defect.

**Comment by mayank2k2** [comment]
attached the document shared by pankaj
[Notification.docx](https://github.com/OUPMATH/OxfrodMaths_Prod/files/448772/Notification.docx)

**Comment by mayank2k2** [comment]
working in production so closing the issue

**Comment by mayank2k2** [comment]
wrongly closed,

**Comment by mayank2k2** [comment]
Please check in production

**Comment by madhumitadey** [comment]
Working fine on production.
