### ISSUE TITLE
Student performance report not viewed properly

### ISSUE THREAD

**Issue by madhumitadey** [OUPMATH/OxfrodMaths_Prod#52]
The student performance report is not viewed properly. (Problem exists in both the reports that are downloaded from Teacher login and Student login). Please see the screenshot below.

![image](https://cloud.githubusercontent.com/assets/16831474/17613927/c0e35480-607f-11e6-8fe1-3699728c299d.png)

**Comment by pankaj44** [comment]
I am looking into it.

**Comment by pankaj44** [comment]
Hi Madhumita,
I have implement the report in different template. Could you please check in UAT and let me know.

**Comment by madhumitadey** [comment]
Hi Pankaj, 

The report format looks good. Working fine on UAT. Let me know when the changes are done on the Production site. I'll check it there as well.

-Regards
Madhumita

**Comment by pankaj44** [comment]
Hi Madhumita,
Production deployment has been completed. Could you please check close the defect.

**Comment by madhumitadey** [comment]
Working fine on production.
