### ISSUE TITLE
Cookie inplementation is not correct

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfrodMaths_Prod#53]
we observe that cookie implementation is not correct, the name of the cookie is firsttime_cookie which should be oup-cookie as a standard. also please find attached document for verify correct implementation.
[International Production Deployment instructions 2.1.docx](https://github.com/OUPMATH/OxfrodMaths_Prod/files/429528/International.Production.Deployment.instructions.2.1.docx)

**Comment by pankaj44** [comment]
I am looking into it.

**Comment by pankaj44** [comment]
Hi Mayan,
I have deployed the changes in UAT. Please clear the cash and cookies and check it.

**Comment by mayank2k2** [comment]
can you name the files where you have made the changes?

**Comment by pankaj44** [comment]
This file is Login.cshtml

**Comment by pankaj44** [comment]
Hi Mayank,
I have done the changes and deployed in QA. Could you please check and let me know.

**Comment by mayank2k2** [comment]
can you check why i am getting style issue
![image](https://cloud.githubusercontent.com/assets/16239450/18041739/90ef1612-6dd9-11e6-9519-bf480714f8e3.png)

**Comment by pankaj44** [comment]
Hi Mayank,
I have done the modification as per our conversation and deployed it in QA. Could you please check and let me know.

**Comment by mayank2k2** [comment]
The message and its height is fine but height of blue bar is more, please compare with production.
[cid:image001.png@01D20387.DB98FAF0]

In production

[cid:image002.png@01D20388.0F2E64E0]
Thanks,
Mayank Mishra

**Comment by pankaj44** [comment]
I have done the changes in QA. Could you please check and let me know your feedback.

**Comment by pankaj44** [comment]
Production deployment has been completed. Please check it and close the defect.

**Comment by mayank2k2** [comment]
working in production, so closing the issue
