### ISSUE TITLE
Email of teacher mandatory in bulk upload sheet 

### ISSUE THREAD

**Issue by madhumitadey** [OUPMATH/OxfrodMaths_Prod#54]
As per FSD, email ID is not mandatory for both teachers and students. Similar instructions were given in the first tab of the bulk upload sheet. However, when email ID was not provided for teacher, the bulk upload process doesn't happen successfully. The error sheet shows "Email cannot be null."

See screenshots below of FSD and error sheet received after the bulk upload process. Please check and make changes according to FSD. 
@mayank2k2 Please check.
![image](https://cloud.githubusercontent.com/assets/16831474/17994880/52cf04f2-6b7a-11e6-9cc3-b90329cd69f8.png)
_Screenshot of FSD_

![image](https://cloud.githubusercontent.com/assets/16831474/17994851/11ba6ea2-6b7a-11e6-842d-c4e5f55abb9f.png)
_Screenshot of error bulk upload sheet_

**Comment by pankaj44** [comment]
I have checked the history from SVN and found that initially code was committed with email validation.(as implemented now )
Could you please let me know what I will do for this validation.

**Comment by mayank2k2** [comment]
comment the code for email validation for teacher

**Comment by mayank2k2** [comment]
please update the instruction sheet accordingly as send in email

**Comment by mayank2k2** [comment]
no change in code

**Comment by pankaj44** [comment]
I have changed the template and moved it in Production. Could you please check and close the defect.

**Comment by madhumitadey** [comment]
This looks fine.
