### ISSUE TITLE
Prod : Unable to track the login IDs (High Priority)

### ISSUE THREAD

**Issue by nehasehgal** [OUPMATH/OxfrodMaths_Prod#55]
Hi,

We are unable to find below login IDs using OUP Admin ID. 
When we try to login, it says “Your subscription has expired. Please contact your school administrator.”

Login ID           Old Password Remarks
Teacher1           Password@1   IDs expired
Student11   Password@1  IDs expired
AnumitaDey  Kolkata@1   IDs expired

Request you to talk to Mayank Mishra. 

Regards,
Neha

**Comment by mayank2k2** [comment]
Hi Pankaj,
Please take a look immediate and reply.

Thanks,
Mayank Mishra

**Comment by pankaj44** [comment]
I am looking into it.

**Comment by pankaj44** [comment]
Could you please let me know the school name.

**Comment by nehasehgal** [comment]
School details is unavailable and we are not able to trace it either.

**Comment by pankaj44** [comment]
Hi Neha,
Could you please check write now in production. If it is working fine then please close the ticket.

**Comment by nehasehgal** [comment]
Hi,

It is working now. Thanks!!

Neha
