### ISSUE TITLE
User upload Excel data not getting uploaded 

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfrodMaths_Prod#56]
I have uploaded two bulk upload sheets against OUP Test School.
- Status,  Error, and Action columns are blank

![image](https://cloud.githubusercontent.com/assets/16831643/18575770/df670624-7bf8-11e6-922a-f7412fbac080.png)
-  User data not getting uploaded in school database

![image](https://cloud.githubusercontent.com/assets/16831643/18575810/321eaf66-7bf9-11e6-8290-38f6dfa0e7f3.png)
- This is one excel
  ![Uploading image.png…]()

**Comment by pankaj44** [comment]
I have tested in UAT and it is working fine. Could you please test again in Production and let me know.
If you are not able to upload successfully in that case please give me the excel sheet.

**Comment by kirti-sharma** [comment]
It is not working fine in UAT also, as visible in the following screen (K S Private School).
![image](https://cloud.githubusercontent.com/assets/16831643/18580576/1197c7f2-7c1a-11e6-816a-f72bced40348.png)

However, please upload the following Excel against **OUP Test School on production server.
[**Upload.xlsx](https://github.com/OUPMATH/OxfrodMaths_Prod/files/476455/Upload.xlsx)

**Comment by pankaj44** [comment]
I have investigated the issue and found that there is problem with excel sheet template. Could you please download a new template and try to upload the data.
I have attached the screen-shot of the template that you are trying to upload in the system also highlighted in red. Please let me know if you have any queries.

![image](https://cloud.githubusercontent.com/assets/16384541/18581249/628cecb6-7c1d-11e6-8d3f-09df4495dff6.png)

**Comment by kirti-sharma** [comment]
Thank you for the prompt response. Data successfully uploaded with new template.
