### ISSUE TITLE
Delete testing related School data from production DB

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfrodMaths_Prod#57]
Hi Pankaj,
These schools and related data need to be deleted from Oxford Math Production DB.

Follow the steps:
1.  List all table that is going to be affected. 
2.  Take a table backup of all affected tables on date and put in OM db eg. For users table backup table would be Backup_Users_19_sept_2016
3.  Call to be me before execute step 4
4.  Execute the script to delete attached schools and related data only, make sure no other school data should be affected.

@Jitendra, can you take a copy of 18_sept 2016 Oxford Math production Database and share to us as preventive action.

[Oxford Math Production Schools for deletion.xlsx](https://github.com/OUPMATH/OxfrodMaths_Prod/files/479783/Oxford.Math.Production.Schools.for.deletion.xlsx)

**Comment by mayank2k2** [comment]
Please list down all the affeected table and put into github

**Comment by pankaj44** [comment]
Please find the affected table below

SCHOOLADDRESSES
UPLOADEDFILES
USERSCHOOLMAPPINGS
CLASSES
USERSECTIONMAPPINGS
USERROLEMAPPINGS
USERADDRESSDETAILS
TASKUSERMAPPINGS
TASKS
ACTIVITYUSERMAPPINGS
ACTIVITIES
SECTIONS
SCHOOLS
NOTIFICATIONUSERMAPPINGS
NOTIFICATIONS
USERS
CLASSSubscriptions

**Comment by mayank2k2** [comment]
All the test data in prod db has been cleaned and below schools are now exists
SchoolId               SchoolCode        SchoolName
382         S382       OUP TEST SCHOOL
393         S393       UTTAM SCHOOL FOR GIRLS
394         S394       HARVEST SCHOOL
395         S395       TAKSHILA SR. SEC. SCHOOL
396         S396       SILVER BELLS CENTRAL SCHOOL
397         S397       Swarnaleela School
398         S398       DIDAC

also attached is the users list for these schools
[UserDetails.xlsx](https://github.com/OUPMATH/OxfrodMaths_Prod/files/486535/UserDetails.xlsx)

**Comment by mayank2k2** [comment]
Closing the issue now
