### ISSUE TITLE
School Performance Report

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfrodMaths_Prod#58]
Hi we need to implement School Performance Report in attached format

The below icon need to be added to school search result in OUP admin login (tool tip: Usage Report)
![image](https://cloud.githubusercontent.com/assets/16239450/19464153/8bfb401c-9517-11e6-84fc-ba5426015f4b.png)

![image](https://cloud.githubusercontent.com/assets/16239450/19464139/6b0f2c24-9517-11e6-9106-8078697e5cbc.png)

once we click the icon it open the below report (similar as welcome letter):

[School PerformanceReport Format.docx](https://github.com/OUPMATH/OxfrodMaths_Prod/files/535252/School.PerformanceReport.Format.docx)

please talk to me about its implementation.

**Comment by pankaj44** [comment]
I am working into it.

**Comment by mayank2k2** [comment]
when can i see the change in UAT

**Comment by pankaj44** [comment]
Hi Mayank,
I have implemented the changes and deployed it in UAT.
I have implemented this before the bulk upload icon. Please check and let me know your feedback.

**Comment by mayank2k2** [comment]
This looks good, few minor suggestion:
1. change User to Users in User tracking as of <date> 
2. add Subscription start and end date below Academic if possible.
3. User Report should be last link (sine this is newly added)
4. Also attach the query in the git hub for review the data

**Comment by pankaj44** [comment]
Hi Mayank,
I have done the modification and deployed in UAT. Could you please re-check and let me know your feedback.

**Comment by mayank2k2** [comment]
. Also attach the query in the git hub for review the data

**Comment by mayank2k2** [comment]
any update

**Comment by pankaj44** [comment]
As discussed,
Please find the attached document for usages report query.

We are doing testing in QA. Once it is completed We will deploy it in UAT.

[UsagesQuery.docx](https://github.com/OUPMATH/OxfrodMaths_Prod/files/566593/UsagesQuery.docx)

**Comment by pankaj44** [comment]
Hi Mayank,
I have done the modification and deployed in UAT. Could you please re-check and let me know your feedback.

**Comment by VrandaNagar** [comment]
Hi Mayank,
I have deployed the changes on prod. Could you please check and let me know your feedback.

**Comment by mayank2k2** [comment]
closing this
