### ISSUE TITLE
UAT incorrect student credential for Oxford Maths

### ISSUE THREAD

**Issue by Kaushik58** [OUPMATH/OxfrodMaths_Prod#60]
We have received the credentials for Oxford Maths both for UAT and Production,
We tried to login with those credentials and only the UAT student credential is not working,
So raising the ticket here as per Mayank's instruction.

UAT Student userid: STUDENTCOGNIZANT

Could you please look into it ASAP.

**Comment by mayank2k2** [comment]
Hi Vrinda, please look into issue

**Comment by VrandaNagar** [comment]
Looking into this.

**Comment by VrandaNagar** [comment]
Hello Mayank,

As a part of debugging this issue i require OUPADMIN  UAT password. 
Please share the password for the same.

Thanks
Vranda

**Comment by mayank2k2** [comment]
Vranda,
You should have these credentials with you, talk to pankaj.

Thanks,
Mayank Mishra

**Comment by VrandaNagar** [comment]
Hi,

I already had words with pankaj and he said the credentials were changed at the time of student usage report UAT testing.

Thanks
Vranda

**Comment by mayank2k2** [comment]
Password for OUPADMIN has never changes. It is same.
Oupadmin@1

Thanks,
Mayank Mishra

**Comment by VrandaNagar** [comment]
Many Thanks.

**Comment by VrandaNagar** [comment]
Hi Kaushik,

Please try with the below credentials :

Username: STUDENTCOGNIZANT
Password: Password@1
Please let me know in case of any difficulty.

Thanks
Vranda
