### ISSUE TITLE
UAT - School admin licence will expire on 31/12/2016 - Need renewal

### ISSUE THREAD

**Issue by Kaushik58** [OUPMATH/OxfrodMaths_Prod#61]
URL - http://www.uat.oxfordmaths.co.in
User ID - S62_4752

Regards,
Kaushik

**Comment by mayank2k2** [comment]
pleae address this issue

**Comment by VrandaNagar** [comment]
Looking into this.

**Comment by VrandaNagar** [comment]
Hi Kaushik,
I have renewd the licence.
Please verify and let me know your feedback.

Thanks!
Vranda
