### ISSUE TITLE
Changes in receipient list of Oxford Maths 'Contact Us Request Form'

### ISSUE THREAD

**Issue by nehasehgal** [OUPMATH/OxfrodMaths_Prod#62]
Hi, 

May I request you to make following changes in the recipients list of Oxford Maths 'Contact Us Request Form'.

Add following email IDs.

1.	Mr Venkateswara Rao : Venkateswara.Rao@oup.com
2.	Mr HunnyAgarwal : Hunny.Agarwal@oup.com
3.	Mr Sandeep Kumar : Sandeep.Kumar@oup.com
4.     Mr Sanjeev Dhiman : Sanjeev.Dhiman@oup.com

Remove following email ID  

1.	Mr Kapil Tuli : Kapil.Tuli@oup.com

Regards,
Neha Sehgal
9990659730

**Comment by VrandaNagar** [comment]
Hi Neha,

I am looking into it.

Thanks!
Vranda

**Comment by VrandaNagar** [comment]
Hi Neha,

Could you please send me the screenshot of the screen you are referring 

Thanks!
Vranda

**Comment by nehasehgal** [comment]
[OM.docx](https://github.com/OUPMATH/OxfrodMaths_Prod/files/892492/OM.docx)
Hi Vranda,

Please refer to the attached sheet.

Regards,
Neha

**Comment by VrandaNagar** [comment]
Hi Neha,

I have done modifications as per requirement and tested the same on QA environment.
For testing in UAT please provide your mail id so that i can deploy the changes in UAT environment.

Thanks!
Vranda

**Comment by nehasehgal** [comment]
Hi Vranda,

My email ID is neha.sehgal@oup.com.

Regards,
Neha

**Comment by VrandaNagar** [comment]
Hi Neha,

I have deployed the changes on UAT with your email id and mine for testing.
Please test the same and let me know your feedback.

Thanks!
Vranda

**Comment by nehasehgal** [comment]
Hi Vranda,

Testing done on UAT and mail received.  Request you to check if you also received the email.  

If everything is okay, please add the requested email IDs and deploy the changes in prod. as well.

Regards,
Neha

**Comment by VrandaNagar** [comment]
Hi Neha,

I have deployed the changes on prod with the requested email id. 
Please verify and let me know your feedback.

Thanks!
Vranda
