### ISSUE TITLE
Oxford Math - Cookies usage message

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfrodMaths_Prod#7]
We are not getting cookies usage message in oxford math as implement in other application, The base requirement has already shared with TCS by Edwin. The message should display for first time users until user agree and proceed.

![cookies message](https://cloud.githubusercontent.com/assets/16239450/14311636/ffc23916-fc05-11e5-9238-4d87459005fe.jpg)

**Comment by mayank2k2** [comment]
@manasghosh81 , I have raised cookies message issue and i need to discuss.

**Comment by mayank2k2** [comment]
@manasghosh81  as discussed this should be displayed when cookies are enable,  after continue this message should disappear.

**Comment by mayank2k2** [comment]
Please explain the usage of below cookies and any other if in the code  
.
![image](https://cloud.githubusercontent.com/assets/16239450/14346058/1144972e-fcce-11e5-9b80-e2cc49e3d635.png)

**Comment by manasghosh81** [comment]
@mayank2k2 :We have fixed this issue.We will share with you list of cookies along with it's purpose.

**Comment by mayank2k2** [comment]
this looks ok in UAT environment, please implement in  oxfordmaths.co.in

**Comment by mayank2k2** [comment]
This is working fine

**Comment by mayank2k2** [comment]
@manasghosh81 by when you will share this information to me.

![image](https://cloud.githubusercontent.com/assets/16239450/14842243/f63d7e7e-0c62-11e6-9749-6b998a8b6d26.png)

**Comment by mayank2k2** [comment]
@manasghosh81   by when you will share this information to me we need it from long time.
