### ISSUE TITLE
‘loading on’ message that comes while we open a topic learning, is wrong

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfrodMaths_Prod#8]
‘loading on’ message that comes while we open a topic learning, is wrong. 

![image](https://cloud.githubusercontent.com/assets/16239450/14457693/fe2dc750-00c9-11e6-8e9a-b63d64264cc6.png)

**Comment by manasghosh81** [comment]
This issue is fixed as the loader file is replaced.

**Comment by mayank2k2** [comment]
@manasghosh81  why you have removed 'On' word from 'Loading on'.

**Comment by mayank2k2** [comment]
closing the issue after discussion with sumit, it should say 'Loading'
