### ISSUE TITLE
content playback issue

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfrodMaths_Prod#9]
At times, when someone tries to open content player after typing **oxfordmaths.co.in** **(without www prefix)**, content player doesn’t open up. This is a known issue and needs to be fixed. 
Could we know how soon we planning to fix it and how?

**Comment by manasghosh81** [comment]
URL redirection needed in IIS label

**Comment by mayank2k2** [comment]
@manasghosh81 by when this will be done.

**Comment by manasghosh81** [comment]
I have fixed this issue.Please check and let me know if you still face this issue,otherwise close it

**Comment by mayank2k2** [comment]
@manasghosh81: The fix must be available in UAT & PROD both the environment

**Comment by mayank2k2** [comment]
I have check this and working in PROD environment if we use oxfordmaths.co.in it converts to www.oxfordmaths.co.in

The same changes need to be configured in UAT as well.

**Comment by mayank2k2** [comment]
This is working in PROD and issue#24 has created to make change in UAT
